### ISSUE TITLE
Tests and CI

### ISSUE THREAD

**Issue by raymondben** [SCAR-sandpit/quantarcticR#1]
Testing has been very minimal so far!
Add `testthat` testing, including on a range of datasets and using all possible mirrors. Add CI via travis, appveyor, use covr, all the usual loot.

**Comment by kimnewzealand** [comment]
I created a couple of unit tests to get the ball rolling.

I noticed two things:

1. The new prompt in the interactive to onLoad option @daranzolin means I can run the tests manually using test() but halts the tests using check(). Just wondering how you suggest the tests select the options?
2. the qa_dataset() is returning class  tbl_df/tbl/data.frame`not yet`qa_dataset`  @raymondben so it is failing.

**Comment by kimnewzealand** [comment]
1. is no longer an issue, Check is now running

**Comment by raymondben** [comment]
Closing: travis (https://github.com/SCAR-sandpit/quantarcticR/commit/45ed6455ee3e304e6a3e426031d3374a5361dad5), appveyor (https://github.com/SCAR-sandpit/quantarcticR/commit/ed601fbfaeadc10668c012ebaa6a8b4c15afb1b7), codecov (https://github.com/SCAR-sandpit/quantarcticR/commit/f759531d401aea41ab89c0db781ea32c2c228141) all enabled
