### ISSUE TITLE
How to handle non-unique layer names?

### ISSUE THREAD

**Issue by daranzolin** [SCAR-sandpit/quantarcticR#14]
There are three non-unique layer names:

- "ADD Coastlines (high)"                      
- "ADD Contours (low, 1000m)"                 
- "ETOPO1/IBCSO/RAMP2 Hillshade (5x v. exag.)"

Attempting to download any of these layers throws an error:
```
> qa_get("ADD Coastlines (high)", verbose = TRUE)
 Error in qa_dataset(name = dataset, refresh_cache = refresh_cache, verbose = verbose) : 
  multiple matching data sets found 
```
Does this need to get resolved in `qa_datasets`? Or perhaps even further upstream?

**Comment by raymondben** [comment]
Have asked the Quantarctica maintainer (Kenny) via email about the duplicates, but I notice that for the second two (Contours & Hillshade) the duplicate layer entries all point to the same source file (shapefile/tif file). So we can just delete the duplicates for those and lose nothing. For the Coastlines, the two versions seem to be line data and polygon data, but we'll see what Kenny says.

**Comment by raymondben** [comment]
As of https://github.com/SCAR-sandpit/quantarcticR/commit/fe654a2b6331da7c9aeab6d3b7ef2e19e9a1ba69 the duplicate layers are dropped and the `id` column has also been dropped from `qa_datasets`, since the `layername` column is now unique (and is what we use to select a `qa_dataset` anyway)
