### ISSUE TITLE
Add print method for dataset objects

### ISSUE THREAD

**Issue by raymondben** [SCAR-sandpit/quantarcticR#2]
The dataset objects are largely just what `bowerbird` uses - could perhaps simplify what the users sees with a custom class and print method here.
This print method should expose the `citation` and `license` components of the dataset definition so that the user is aware of them.
Also:
- add `cached` indicator to dataset object, similar to that in the `qs_datasets`
- perhaps keep track of download date/time for each data set and show it in the print method
- can we make the object returned by `qa_get` be similar to that from `qa_dataset`?

**Comment by kimnewzealand** [comment]
I have created a new qa_print function. It is a first version with a few placeholder to test out the new workflow process and to see if this is in line with the thinking of what this should look like.

I have made a couple of assumptions that this will print an object from the qa_get function and that the citation format will be similar to the library(quantarticR) message.

I have also left it on the addprint branch that I created. I expect there will be a few reviews and iterations to get it master branch ready :

**Comment by kimnewzealand** [comment]
OK I have had a bit of a git fail. I tried to use the RStudio git tab to see if it is easier but I just can't find the code on my github anywhere on the branch addprint. I am used to git bash....

In interest of time to 'publish' my code, here is my code update trying out the S3 method. It did seem to work after building it which is the good news :) 

#' Print details of a Quantarctica data set object
#'
#' @param nameobject tibble: the name of the data set output variable assigned to qa_get
#'
#' @return Message and an S3 class

## Second version of this print method is to use S3 methods
## First define the S3 method with base R `UseMethod()`
#' @export
qa_print <- function(nameobject) UseMethod("qa_print")

#' @export
qa_print.default <- function(nameobject, ...){

  citation_message(nameobject)

  warning(paste("qa_print does not know how to handle object of class ",
                  class(nameobject),
                  "and can only be used on classe tibble or dataframe"))
  ## Further methods can be added for other classes


}

#' @export
qa_print.tibble <- function(nameobject, ...){

  citation_message(nameobject)
  # Placeholder to add cached indicator, ( to be added to qa_get first?)
  # Placeholder to add download date/time , ( to be added to qa_get first?)
  # Placeholder for out

}

#' @export
qa_print.data.frame <- function(nameobject, ...){

  citation_message(nameobject)
  # Placeholder to add cached indicator, ( to be added to qa_get first?)
  # Placeholder to add download date/time , ( to be added to qa_get first?)
  # Placeholder for out

}

## Internal function to print citation message
citation_message <- function(nameobject) {

  # Replicate the message format from library(quantarticR).
  # The qa_get function does not currently return license and citation components, is the license or citation expected to change? or can we hardcode this information?
  print("Quantarctica is made available under a CC-BY license")
  print(paste0("If you use ",nameobject$name, ", please cite it:"))
  # Print citation details
  print(paste0("Matsuoka, K., Skoglund, A., & Roth, G. (2018). Quantarctica ", nameobject$name, ". Norwegian Polar Institute. https://doi.org/10.21334/npolar.2018.8516e961"))
}

**Comment by raymondben** [comment]
Thanks Kim- I'll have a look tonight.

**Comment by raymondben** [comment]
Minor update: the current master branch has a trivial print method for `qa_dataset` objects, but plenty of room to customize this to a more user-friendly output.
One issue to be aware of: most data sets appear to have their proper citation information buried in their abstract text. The current `citation` field in the `qa_dataset` object is unlikely to match this information (it's just the main Quantarctica citation with the name of the dataset inserted). Probably a good idea to resolve this where possible.

**Comment by raymondben** [comment]
e83ed6971d8f3397dba1d29fbb1193930a714420
