### ISSUE TITLE
Dataset sizes

### ISSUE THREAD

**Issue by raymondben** [SCAR-sandpit/quantarcticR#4]
Really need to know dataset sizes so that users know what they are in for before they launch a download. Size should be added to the object constructed within `qa_dataset`.
I don't think the .qgs project file contains size information, so it will need to come from elsewhere.

**Comment by daranzolin** [comment]
Looks like we could possibly get it here: http://data.pgc.umn.edu/gis/packages/quantarctica/Quantarctica3/

**Comment by daranzolin** [comment]
Might need to look elsewhere, `rvest` couldn't read the html on several pages, and I could thus only obtain size data on only 116 of our 269 datasets. [Gist here.](https://gist.github.com/daranzolin/fe606a2584216e1fe314b4169abada93)

**Comment by raymondben** [comment]
I am thinking that since the Quantarctica data collection doesn't get updated often, the easiest solution might be just to figure out individual dataset sizes by looking at a local copy of the full data collection, and store this as a data object in the package?

**Comment by daranzolin** [comment]
That sounds right, but I don't think I have enough space on my hard drive. Is it times like these where one would turn to the cloud? Like spin up a VM somewhere, run the downloading script, and then extract the file info? 

Regardless, I kept hacking out of habit and was able to scrape the file name and sizes from those urls. 

[quantarcticR_dataset_info.txt](https://github.com/SCAR-sandpit/quantarcticR/files/2716910/quantarcticR_dataset_info.txt)

**Comment by kimnewzealand** [comment]
While creating the vignette I randomly picked a very large dataset. The sizing would be useful to know before starting the download.

icemask <- qa_get("BEDMAP2 Ice outline mask", verbose = TRUE)

**Comment by raymondben** [comment]
Done, I think, see https://github.com/SCAR-sandpit/quantarcticR/commit/251125568605e7769e99715e9a61e55bf4881fac. It relies on a pre-downloaded copy of the full data set and saves the sizes into a data object (see the script in `data-raw`). Will leave the issue open until we're happy that this is a satisfactory solution (ideally I'd prefer not to rely on a saved copy of this information in the package, because if the saved info gets out of sync with the live info in the real world, the sizes won't be right. But having the already-saved info directly in the package will make things a lot faster, so I think the tradeoff is worth it)

**Comment by raymondben** [comment]
Closing
