### ISSUE TITLE
Change refresh_cache to clobber

### ISSUE THREAD

**Issue by raymondben** [SCAR-sandpit/quantarcticR#5]
Change the `refresh_cache` argument (logical) to `clobber` to match bowerbird's clobber behaviour (0 = don't re-download, 1 = re-download if newer, 2 = re-download regardless)

**Comment by trivialspace** [comment]
I created a branch and made the modifications. I still need to test that behavior is as expected (this could be a first unit test).

**Comment by raymondben** [comment]
@trivialspace what if you set up testing in this branch (should just be a matter of running `usethis::use_testthat` and then we can start populating tests?

**Comment by raymondben** [comment]
Manually merged this code into master, because master is changing rapidly. See https://github.com/SCAR-sandpit/quantarcticR/commit/bf7cd05ed1d46b78a3df0488f82900fc4e8f42fe
