### ISSUE TITLE
Check cache_dir structure

### ISSUE THREAD

**Issue by raymondben** [SCAR-sandpit/quantarcticR#6]
If the user provides an actual path to `qa_cache_dir`, should we check to make sure it looks right? It needs to point to the directory where the .qgs index file is kept. If the user inadvertently points to e.g. the parent or child directory, things will be re-downloaded unnecessarily.
Note that the .qgs index file might not exist - the user might be providing a brand new path. So that file not existing is not an error, but if it exists nearby then it might be.

**Comment by daranzolin** [comment]
Anything we can do to avoid unexpected and unwanted downloading is a plus to me. I'll start here!

**Comment by daranzolin** [comment]
I do not love how `qa_cache_dir` can perform three separate tasks (print the cache directory, change the directory, or change the cache behavior). My thought here is to refactor into a separate, more explicit function: `qa_set_cache_dir`. If the user wants to print the directory to the console, they can use getOption, or a helper `qa_option` function, maybe. 

Thoughts?

**Comment by raymondben** [comment]
https://github.com/SCAR-sandpit/quantarcticR/commit/6a4375fd10de10a3cd612e2b098a6ddc5c231f6d
