### ISSUE TITLE
Better package name?

### ISSUE THREAD

**Issue by raymondben** [SCAR-sandpit/quantarcticR#7]
Is there a better one? Just because "quantarcticR" is a pain to type!

**Comment by mdsumner** [comment]
quantarc - the only thing I've sort of liked, will keep pondering

**Comment by daranzolin** [comment]
It breaks all of Hadley's rules for naming packages, but I would enjoy:
```
library(penguin)
```

**Comment by kimnewzealand** [comment]
Otherwise I would also go with existing unless you need fit that on to a hex sticker?

**Comment by raymondben** [comment]
Ooh, I quite like that ...

**Comment by raymondben** [comment]
Executive decision: leave as is.
