### ISSUE TITLE
Add more dataset info

### ISSUE THREAD

**Issue by raymondben** [SCAR-sandpit/quantarcticR#8]
The .qgs file contains more information on each data set, which should be returned as part of the `qa_datasets` and `qa_dataset` functions. 
The extra information includes the abstract (description) of each data set, and potentially also styling information such as the preferred colour map. See "TODO" code snippet in function dataset_qgs_to_tibble (datasets.R)

**Comment by daranzolin** [comment]
Thoughts on having two separate functions, `qa_raster_datasets` and `qa_vector_datasets`? The objects have different attributes/columns, and while binding them altogether is doable, it's somewhat unwieldy.

**Comment by raymondben** [comment]
I haven't thought about this deeply, but what if `qa_datasets` remains largely as-is, but with a `type` column added (which can take values "vector" or "raster") - so that the user can still get an overview of all data layers regardless of type. Then either separate `qa_raster_dataset` and `qa_vector_dataset` functions that return the details of an individual dataset (and these will vary in attributes/cols between the two functions). Or a single `qa_dataset` function, but it would have to return a differently-structured object depending on whether the requested data set was vector or raster, so maybe the separate functions are clearer.
